### PR TITLE
SPRK-3350 fix(oauth2_provider): Add missing migrations for models

### PR DESCRIPTION
**Pull request by crbunney**
To fix an error due to Django querying a table that doesn't exist in the database when attempting to delete a Spark Client.

These models aren't used by Spark. However, due to the way Django emulates cascading deletes, their absence from the database causes an error when deleting Spark Clients because of the `oauth2_provider.provider.oauth2.models.Client` models' foreign key to `settings.AUTH_USER_MODEL`.

This is because Django doesn't use the database's cascading delete feature, and emulates it in python instead. It detects the ForeignKey field in the model code and attempts to delete any related records from the table - leading to the error

### CODE REVIEW

**Comment by JacobHicksSponge** [comment]
Looks good to me.  Just to confirm - these tables already exist in the database?  Does that mean we should manually mark this migration as applied as part of the deployment?

**Comment by crbunney** [comment]
> Looks good to me. Just to confirm - these tables already exist in the database? Does that mean we should manually mark this migration as applied as part of the deployment?

No, they don't exist in the database, that's the source (I think) of my issue. I don't think it normally causes a problem because these models are only used if you deploy the LRS as a standalone app, which we never do.

But it seems to cause a problem when trying to delete clients from Spark because Django traces all the ForeignKeys back to their source models and runs queries on the underlying tables. That's what I think is causing this error when I run `Client.delete()` (that's a Spark client, different from the client in this repo):
```
CommandError: Database error when deleting client_blxguasmxw: relation "oauth2_provider_client" does not exist
LINE 1: ...ret", "oauth2_provider_client"."client_type" FROM "oauth2_pr...
```

Happy to chat it over if that'd be clearer - it seems a bit random to me

**Comment by JacobHicksSponge** [comment]
> > Looks good to me. Just to confirm - these tables already exist in the database? Does that mean we should manually mark this migration as applied as part of the deployment?
> 
> No, they don't exist in the database, that's the source (I think) of my issue. I don't think it normally causes a problem because these models are only used if you deploy the LRS as a standalone app, which we never do.
> 
> But it seems to cause a problem when trying to delete clients from Spark because Django traces all the ForeignKeys back to their source models and runs queries on the underlying tables. That's what I think is causing this error when I run `Client.delete()` (that's a Spark client, different from the client in this repo):
> 
> ```
> CommandError: Database error when deleting client_blxguasmxw: relation "oauth2_provider_client" does not exist
> LINE 1: ...ret", "oauth2_provider_client"."client_type" FROM "oauth2_pr...
> ```
> 
> Happy to chat it over if that'd be clearer - it seems a bit random to me

Yeah, that would be good - maybe straight after the sprint review?  Would be good to see how it's behaving on your local system too with/without this migration applied

**Comment by dbramwell** [comment]
It feels weird to me to add things to the database that we're not using. Have you checked a schema that's existed for a while (pre all the django upgrades), there could be a chance that these do exist in some of the older schemas, django/south used to do a database "sync" for models in apps that didn't have migrations.

**Comment by dbramwell** [comment]
Another question is whether we use any of the tables from `oauth2_provider`? Could we remove that app from the list of installed apps in Spark? That might sort it

**Comment by crbunney** [comment]
> Another question is whether we use any of the tables from `oauth2_provider`? Could we remove that app from the list of installed apps in Spark? That might sort it

Spark doesn't, but it seems they're referenced by the `lrs` repo, which is why they're added to Spark's `INSTALLED_APPS`. I did consider removing them, but that seemed like a potentially riskier change, as I wasn't all that confident we'd be able to detect if doing so created bugs.

Just tried commenting it out and Spark won't start:
``` <snip>
  File "/app/bolt/urls.py", line 12, in <module>
2024-04-16T09:07:08.620476378Z     from lrs import views as lrs_views
2024-04-16T09:07:08.620482128Z   File "/src/lrs/lrs/views.py", line 22, in <module>
2024-04-16T09:07:08.620483337Z     from .util import req_validate, req_parse, req_process, XAPIVersionHeaderMiddleware, accept_middleware, \
2024-04-16T09:07:08.620484670Z   File "/src/lrs/lrs/util/req_validate.py", line 9, in <module>
2024-04-16T09:07:08.620495795Z     from .Authorization import auth
2024-04-16T09:07:08.620499170Z   File "/src/lrs/lrs/util/Authorization.py", line 12, in <module>
2024-04-16T09:07:08.620560212Z     from oauth2_provider.provider.oauth2.models import Client
2024-04-16T09:07:08.620565795Z   File "/src/lrs/oauth2_provider/provider/oauth2/models.py", line 24, in <module>
2024-04-16T09:07:08.620567170Z     class Client(models.Model):
2024-04-16T09:07:08.620568545Z   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 113, in __new__
2024-04-16T09:07:08.620655878Z     raise RuntimeError(
2024-04-16T09:07:08.620663378Z RuntimeError: Model class oauth2_provider.provider.oauth2.models.Client doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

I think I've tried adding app labels in the past and backed out because it seemed to cause a chain of other issues. I'm guessing adding the app to INSTALLED_APPS is how we worked around this issue

**Comment by dbramwell** [comment]
Hmm, that's annoying. I guess it's safe to assume that as the tables don't exist we're not using the functions that call those models. Wonder if it's time we did a big LRS prune? There's loads of stuff in there we don't use and we're not trying to keep in line with upstream anymore

**Comment by crbunney** [comment]
> It feels weird to me to add things to the database that we're not using. Have you checked a schema that's existed for a while (pre all the django upgrades), there could be a chance that these do exist in some of the older schemas, django/south used to do a database "sync" for models in apps that didn't have migrations.

I've just checked 9 clients that I know display the bug:
* `client_atuazkbgrz` - created 08/09/22
* `client_alhodgwyvr` - created 01/02/24

And I've been deleting clients created since 08/08/22 in date order, and the first occurrence of the issue since that date is `client_altugkyjvp`, created 2022-09-08 16:39:38.353404+00:00`

I don't remember when we switched from South to django migrations, do you?

I also noticed that we've added migrations for the `oauth_provider` app in  #7, but the models in this PR don't get picked up by the standard `makemigrations` command. I had to explicitly run `./manage.py makemigrations oauth2` to get these migrations to generate

**Comment by crbunney** [comment]
> Hmm, that's annoying. I guess it's safe to assume that as the tables don't exist we're not using the functions that call those models. Wonder if it's time we did a big LRS prune? There's loads of stuff in there we don't use and we're not trying to keep in line with upstream anymore

I've assumed the same thing, especially as this all seems to be to do with OAUTH, and we have our own OAUTH stuff in the main Spark repo.

Yea, I think the way we're using lrs as a library when it was created as a standalone application is part of why we're having weird issues like this. A prune could be a very good thing, although I avoided it for this work as I felt it was a more invasive and risky change.

Creating our own LRS like was talked about a while back would be a good improvement too

**Comment by dbramwell** [comment]
> > Hmm, that's annoying. I guess it's safe to assume that as the tables don't exist we're not using the functions that call those models. Wonder if it's time we did a big LRS prune? There's loads of stuff in there we don't use and we're not trying to keep in line with upstream anymore
> 
> I've assumed the same thing, especially as this all seems to be to do with OAUTH, and we have our own OAUTH stuff in the main Spark repo.
> 
> Yea, I think the way we're using lrs as a library when it was created as a standalone application is part of why we're having weird issues like this. A prune could be a very good thing, although I avoided it for this work as I felt it was a more invasive and risky change.
> 
> Creating our own LRS like was talked about a while back would be a good improvement too

Rather than pruning too deeply could you try just pruning the specific bits using the models, eg replace https://github.com/sponge-learning/ADL_LRS/blob/master/lrs/util/req_parse.py#L155-L163 with just a `raise OauthUnauthorized("Cannae do it")`

This doesn't seem to be used anywhere so can be binned: https://github.com/sponge-learning/ADL_LRS/blob/master/lrs/util/Authorization.py#L30C5-L49

We also don't use these endpoints:
https://github.com/sponge-learning/ADL_LRS/blob/master/lrs/views.py#L315
https://github.com/sponge-learning/ADL_LRS/blob/master/lrs/views.py#L440
https://github.com/sponge-learning/ADL_LRS/blob/master/lrs/views.py#L424

Think that removes all references to the oauth2.models

**Comment by dbramwell** [comment]
Actually, you could probably quite easily get it removed all together. Think there's only a couple more unused views that use it

**Comment by crbunney** [comment]
Replaced by #36

**Pull request closed without merging**
