### PR TITLE
SPRK-2560: update except case for python3

### PR DESCRIPTION
**Pull request by IhorKalhanov**
fixed issue 
"catching classes that do not inherit from BaseException is not allowed"

### CODE REVIEW

**Comment by dbramwell** [comment]
Is the only change (other than formatting) swapping the ValidationError for SuspiciousOperation?

**Comment by IhorKalhanov** [comment]
Yes, you're right, I replaced it and combined it into one group where you need to return status code 400.

Maybe I shouldn't have done the indentation formatting? (my Py Charm did it)

**Comment by dbramwell** [comment]
Yeah, it'd be easier to review without the formatting, but some editors do just do it. At some point we want to go through and format everything with `black` or something, but I'm not bothered about it for now.

How do we know that swapping ValidationError for SuspiciousOperation is the right thing to do?

**Comment by IhorKalhanov** [comment]
I added this because I saw in the next release of the adl lrs library, they added SuspiciousOperation this instead of HttpResponseBadRequest because it includes this error https://docs.djangoproject.com/en/1.11/ref/exceptions/#django.core.exceptions.SuspiciousOperation. It also has some additional interesting features that I think might be useful for us in the future.


When I was doing the refactor I think I accidentally removed ValidationError, now I'll put it back

**Comment by IhorKalhanov** [comment]
I will test if everything works correctly now

**Comment by IhorKalhanov** [comment]
I checked locally and everything seems to work correctly
Do you think I need to remove the additional operator(SuspiciousOperation)

**Review by dbramwell — APPROVED** [review]

**Pull request merged**
